FROM debian:bookworm-slim

RUN apt clean && apt update && apt update -y

# 検証用ツール
RUN apt install -y vim curl \
        # ping command
        iputils-ping \
        # ip command
        iproute2 \
        # traceroute command
        traceroute \
        # ネットワークパケットをキャプチャして表示するためのユーティリティ
        tcpdump

WORKDIR /tmp
RUN curl -OL https://github.com/prometheus/node_exporter/releases/download/v1.8.2//node_exporter-1.8.2.linux-amd64.tar.gz && \
        tar xzvf node_exporter-1.8.2.linux-amd64.tar.gz && \
        cd node_exporter-1.8.2.linux-amd64 && \
        cp node_exporter /usr/local/bin
WORKDIR /usr/local/bin
CMD [ "./node_exporter" ]